
development:
  encoding: unicode
  adapter: postgresql
  username: Chandler
  database: heroku_postgresql_cyan_url
  host: localhost

test:
  encoding: unicode
  adapter: postgresql
  username: Chandler
  database: heroku_postgresql_cyan_url
  host: localhost

production:
  encoding: unicode
  adapter: postgresql
  username: cheshireoctopus
  database: HEROKU_POSTGRESQL_CYAN_URL

